# The URL the site will be built for
base_url = "https://creamakerspace.com"
title = "Crea Makerspace"
description = "Renton makerspace providing classes, events, and shared access to a collaborative space and equipment."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "makerspace"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo = "/images/logo.png"
copyright = "Crea Makerspace"
newsletter_link = "https://000a4b3c.sibforms.com/serve/MUIEACsqgUfzNUnjRwJxuXpeFa3tgRjoySDVAZ2Va8qywAkO8O95A5DNq4ABmRQdA35MONBjUMQcI2HYqi_WlUfF75SImq68Y_fqTmfLSmkvzbqdRA-H97mmU4iQ5C86Drh-VtOvvINZn4b1qtMg7iFjpISoJ0lEzgwTezyuQcm7o6jl0dOEFP6ilAo3C2immGAU9Nnt7DCgl4dC"
contact_email = "hi@creamakerspace.com"
contact_email_html = "hi@crea<span>makerspace</span>.com"
address = "Address TBD"

# analytics
goatcounter = "https://crea.goatcounter.com/count"

[extra.social]
facebook = "https://www.facebook.com/CreaMakerspace/"
# linkedin = "https://www.linkedin.com/company/crea-makerspace"
# instagram = "https://www.instagram.com/CreaMakerspace/"
# discourse = ""

# [[extra.nav]]
# text = "Take a Class"
# link = "/classes"

# [[extra.nav]]
# text = "Bring a Group"
# link = "/groups"

# [[extra.nav]]
# text = "Join our Community"
# link = "/community"

# [[extra.nav]]
# text = "Events"
# link = "/events"

# [[extra.nav]]
# text = "Makers"
# link = "/makers"

# [[extra.nav]]
# text = "Partners"
# link = "/partners"

[[extra.nav]]
text = "Blog"
link = "/blog"

[[extra.nav]]
text = "About"
link = "/about"


[[extra.footer_nav]]
text = "Classes"
# link = "/classes"

[[extra.footer_nav]]
text = "Groups"
# link = "/groups"

[[extra.footer_nav]]
text = "Membership"
# link = "/community"

[[extra.footer_nav]]
text = "Partnership"
# link = "/partners"

[[extra.footer_nav]]
text = "Events"
# link = "/events"

[[extra.footer_nav]]
text = "Equipment"
# link = "/equipment"

[[extra.footer_nav]]
text = "Makers"
# link = "/makers"

[[extra.footer_nav]]
text = "Policies & Rules"
# link = "/policies"

[[extra.footer_nav]]
text = "Blog"
link = "/blog"
