name = "makerspace"
description = "Promote a makerspace"
license = "MIT"
homepage = "https://github.com/creamakerspace"
# The minimum version of Zola required
min_version = "0.16.1"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Tony Nowell"
homepage = "https://anowell.com"

