on:
  pull_request:
    branches:
      - main
  workflow_call:

name: Build

jobs:
  scraper:
    name: Site Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Get Zola
        run: docker pull ghcr.io/getzola/zola:v0.16.0

      - name: Build Site
        run: docker run -u "$(id -u):$(id -g)" -v $PWD:/app --workdir /app ghcr.io/getzola/zola:v0.16.0 build

      - name: Upload built site archive
        uses: actions/upload-artifact@v2
        with:
          name: site-archive
          path: public

