name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: creamakerspace/website/.github/workflows/build.yml@main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built site archive
        uses: actions/download-artifact@v4
        with:
          name: site-archive
          path: public

      - name: public directory exists
        run: test -d public && ls -R public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public

